### ISSUE TITLE
Падает на рекурсивных ссылках в модели

### ISSUE THREAD

**Issue by valeevr** [kostya05983/spring-generate-plugin#4]
![image](https://github.com/kostya05983/spring-generate-plugin/assets/25036644/2bb77ad3-de1b-4743-9081-20902e7e1d32)

**Comment by kostya05983** [comment]
Пофиксил, в скором времени выйдет обновление 1.1.1

**Comment by kostya05983** [comment]
Зарелизили, поправлено в 1.1.1
